//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OL
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Персонал.
    /// </summary>
    // *** Start programmer edit section *** (Персонал CustomAttributes)

    // *** End programmer edit section *** (Персонал CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПерсоналE", new string[] {
            "Контакты as \'Контакты\'",
            "ФИО as \'ФИО\'",
            "Должности as \'Должности\'",
            "Должности.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Должности.Наименование"})]
    [MasterViewDefineAttribute("ПерсоналE", "Должности", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ПерсоналL", new string[] {
            "Контакты as \'Контакты\'",
            "ФИО as \'ФИО\'",
            "Должности.Наименование as \'Наименование\'"})]
    public class Персонал : ICSSoft.STORMNET.DataObject
    {
        
        private string fКонтакты;
        
        private string fФИО;
        
        private IIS.OL.Должности fДолжности;
        
        // *** Start programmer edit section *** (Персонал CustomMembers)

        // *** End programmer edit section *** (Персонал CustomMembers)

        
        /// <summary>
        /// Контакты.
        /// </summary>
        // *** Start programmer edit section *** (Персонал.Контакты CustomAttributes)

        // *** End programmer edit section *** (Персонал.Контакты CustomAttributes)
        [StrLen(255)]
        public virtual string Контакты
        {
            get
            {
                // *** Start programmer edit section *** (Персонал.Контакты Get start)

                // *** End programmer edit section *** (Персонал.Контакты Get start)
                string result = this.fКонтакты;
                // *** Start programmer edit section *** (Персонал.Контакты Get end)

                // *** End programmer edit section *** (Персонал.Контакты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Персонал.Контакты Set start)

                // *** End programmer edit section *** (Персонал.Контакты Set start)
                this.fКонтакты = value;
                // *** Start programmer edit section *** (Персонал.Контакты Set end)

                // *** End programmer edit section *** (Персонал.Контакты Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Персонал.ФИО CustomAttributes)

        // *** End programmer edit section *** (Персонал.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Персонал.ФИО Get start)

                // *** End programmer edit section *** (Персонал.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Персонал.ФИО Get end)

                // *** End programmer edit section *** (Персонал.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Персонал.ФИО Set start)

                // *** End programmer edit section *** (Персонал.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Персонал.ФИО Set end)

                // *** End programmer edit section *** (Персонал.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Персонал.
        /// </summary>
        // *** Start programmer edit section *** (Персонал.Должности CustomAttributes)

        // *** End programmer edit section *** (Персонал.Должности CustomAttributes)
        [PropertyStorage(new string[] {
                "Должности"})]
        [NotNull()]
        public virtual IIS.OL.Должности Должности
        {
            get
            {
                // *** Start programmer edit section *** (Персонал.Должности Get start)

                // *** End programmer edit section *** (Персонал.Должности Get start)
                IIS.OL.Должности result = this.fДолжности;
                // *** Start programmer edit section *** (Персонал.Должности Get end)

                // *** End programmer edit section *** (Персонал.Должности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Персонал.Должности Set start)

                // *** End programmer edit section *** (Персонал.Должности Set start)
                this.fДолжности = value;
                // *** Start programmer edit section *** (Персонал.Должности Set end)

                // *** End programmer edit section *** (Персонал.Должности Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПерсоналE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПерсоналE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПерсоналE", typeof(IIS.OL.Персонал));
                }
            }
            
            /// <summary>
            /// "ПерсоналL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПерсоналL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПерсоналL", typeof(IIS.OL.Персонал));
                }
            }
        }
    }
}
